# Generated by Django 4.2 on 2023-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_alter_program_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
