# Generated by Django 4.2 on 2023-06-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='files',
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
