# Generated by Django 4.2 on 2023-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_alter_request_files_alter_request_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'cash'), ('BANK_TRANSFER', 'bank_transfer'), ('CHECK', 'check')], max_length=50, null=True),
        ),
    ]
