# Generated by Django 4.2 on 2023-06-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_fund_allocated_chapters_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='allocated_chapters_amount',
            new_name='allocated_chapters_amnt',
        ),
    ]
