# Generated by Django 4.2 on 2023-06-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0016_rename_allocated_chapters_amount_fund_allocated_chapters_amnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='allocated_chapters_amnt',
        ),
    ]
