# Generated by Django 4.2 on 2023-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0019_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='GRANT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='allocated_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='remaining_allocated_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='allocated_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='remaining_allocated_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
